---
title: "Practical Machine Learning - Project WriteUp"
author: "user_id 0c78b2588b0c02a54a2c07955323b44e"
date: 'Coursera - March 2015'
output:
  html_document:
    css: ../../../00_Common/CustomRmdStyle.css
---

## REMOVAL NOTICE

<div id="BoxWarning">
The Project WriteUp page has been rolled back to hide it from public view. This is intentional to respect **Coursera Honor Code**. My original work is still available. If you are Coursera Staff and wants to review/audit my work, please contact me through my Coursera UserID above.
</div>
<br/>
[Coursera Honor Code](https://www.coursera.org/about/terms/honorcode):

All students participating in the class must agree to abide by the following code of conduct:

- I will register for only one account.

- My answers to homework, quizzes, exams, projects, and other assignments will be my own work (except for assignments that explicitly permit collaboration).

- **I will not make solutions to homework, quizzes, exams, projects, and other assignments available to anyone else** (except to the extent an assignment explicitly permits sharing solutions). This includes both solutions written by me, as well as any solutions provided by the course staff or others.

- I will not engage in any other activities that will dishonestly improve my results or dishonestly improve or hurt the results of others.


## THANK YOU

If you are not Coursera Staff and somehow is aware of this page. I am sorry the page is no longer available. If you were one of my graders and kept a copy of my work. I would like to ask you to keep it private for yourself only. Please **DO NOT** publish it anywhere. Thank you for your help to encourage future students to work by themselves.